language: php
php:
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
 - composer self-update
 - composer install --no-interaction --dev
before_script:
  - mkdir -p build/
  - mkdir -p build/logs
  - php ./tests/database.php
  - php -S localhost:8005 -t tests/APP/public/&
script:
 - find src/ -name '*.php' -print0 | xargs -0 -L 1 php -l
 - find tests/ -name '*.php' -print0 | xargs -0 -L 1 php -l
 - php vendor/bin/phpunit
after_script:
 - php vendor/bin/coveralls -v
 - php vendor/bin/codacycoverage clover build/logs/clover.xml
